import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Matrix from '../components/Matrix/matrix'
import Matrix3dScene from '../components/Matrix/matrix3dScene'
import React from 'react';
import { useState, useEffect } from "react";

const Home: NextPage = () => {

  const [fontAvailable, setfontAvailable] = useState(false);
  const [matrixCanvasAvailable, setMatrixCanvasAvailable] = useState(false)

  useEffect(() => {
    // check if font is available
    if (!fontAvailable) {       
      document.fonts.load('20px "Matrix"').then(() => {
        setfontAvailable(true);
      })
    } 
  });

  
  
    

  return (
    <div>
      <Head>
        <title>Richard PERRET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main> 
        {fontAvailable 
          ? 
            <>
              <Matrix></Matrix>
              {matrixCanvasAvailable
                ?
                  <Matrix3dScene canvas={(document.querySelector('#matrixCanvas') as HTMLCanvasElement)} /> 
                :
                  null
              }            
            </>        
          : <span>not available yet</span>              
        }
      </main>
    </div>
  )
}

export default Home
